on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Deploy
        run: scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Verify gcloud installation
        run: gcloud info

      - name: Build and push Docker image
        run: |
          PROJECT_ID=$(gcloud config get-value project)
          IMAGE_NAME=notely
          REGION=us-central1  # change to your region
          IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/notely/$IMAGE_NAME:latest"

          echo "Building and pushing $IMAGE_URI"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"